### ISSUE TITLE
TTF-Excluding Hangeul empty glyphs- did not work with Glyphs custom parameter 

### ISSUE THREAD

**Issue by minjooham** [hyper-type/hahmlet#4]
Adding Glyphs custom Parameter to exclude Hangeul empty glyphs for TTF files did not work.
Making TTF with Fontmake, it seems they ignore custom parameters in Glyphs.
Is there a better way *to exclude hangeul empty glyphs* from ttf files?

@davelab6 @Mark2Mark

**Comment by Mark2Mark** [comment]
[🔗 crosslinking](https://github.com/googlefonts/fontmake/issues/257)

**Comment by punchcutter** [comment]
If all you want is to not include certain glyphs in the generated TTF you can add them to the designspace file with a     public.skipExportGlyphs key.

**Comment by minjooham** [comment]
@punchcutter Thanks for your feedback. We tried what you mentioned.
We put these into the “designspace file” right after the `</instances>` closing tag. 

```
  <lib>
	<dict>
		<key>public.skipExportGlyphs</key>
		<string>uniAC02</string>
	</dict>
  </lib>
```
We tried several ttf generations, with that test glyph with unicode-Name and also with niceName and both “gagg-ko” and “uniAC02”did not working. 
**Is this right code and right place to put?**

By the way there is already the information
 "Remove Glyphs" along with all the glyph names in the .designspace file, which we added as a custom parameter from Glyphs.
**Fontmake could make use of that?** 

@davelab6 @Mark2Mark

<img width="639" alt="스크린샷 2020-10-21 19 49 02" src="https://user-images.githubusercontent.com/55446258/96767875-6b126580-13dd-11eb-8b6d-fae855126e08.png">

**Comment by punchcutter** [comment]
Almost. The <string>glyphname</string> needs to be inside an array. So something like
```
<lib>
    <dict>
        <key>public.skipExportGlyphs</key>
        <array>
            <string>gagg-ko</string>
        </array>
    </dict>
</lib>
```

**Comment by davelab6** [comment]
I hope @aaronbell could comment on this when he has a moment :)

**Comment by aaronbell** [comment]
> Glyphs custom Parameter to exclude Hangeul empty glyphs
I'm not exactly sure what you mean by this. Are you referring to the "Remove Glyphs" custom parameter?

Per the [fontmake code](https://github.com/googlefonts/fontmake/blob/master/Lib/fontmake/font_project.py) and additional discussion [here](https://github.com/googlefonts/glyphsLib/issues/295), fontmake only supports two Glyphs-inbuilt mechanisms for determining glyph export: global "Keep Glyphs" and the per-glyph export flag binary.

Given this, I'd suggest either setting all empty glyphs to non-exporting, or to use the "Keep Glyphs" custom parameter and include everything _except_ the empty glyphs. I think you could write a script that uses either approach pretty easily (for glyph in Hangul unicode range, if no components / no paths, set as non-exporting or add to Keep Glyphs). Else, Smart Filtering will make it relatively easy. 

Alternately you can use external methods:
1) As Zachary recommended, use of public.skipExportGlyphs will let you exclude glyphs, but it is still manually created. If you're using a build script, you could potentially autogenerate this by reading the custom parameter and insert it into the designspace doc. 

2) Use pysubset as part of your build process. It is something of a post-production step, but you could create a list of all empty glyphs (either manually, or by script) and use the subset command to clip out all the glyphs you don't want. 

3) If you are exporting from Glyphs to a UFO, you can load up the UFO using ufoLib prior to running fontmake and then delete glyphs using glifLib (could even just run a loop - "for all glyphs in this unicode range, if no content, delete"). Given that you (probably) don't have to worry about modifying the feature code, this is a pretty simple mechanism to just delete a bunch of glyphs.

**Comment by davelab6** [comment]
> Use pysubset as part of your build process.

That seems useful to me, since then there are builds with and without the blank glyphs. 

https://github.com/fonttools/fonttools/blob/master/Snippets/rename-fonts.py can also be helpful

**Comment by minjooham** [comment]
@aaronbell  "Keep Glyphs" worked well. Thanks you for the kind explanation.
