### ISSUE TITLE
Solve nested components

### ISSUE THREAD

**Issue by davelab6** [hyper-type/hahmlet#5]
@minjooham said,

> So now we have only one "fail" from fontbakery: "found-nested-components" 
>
> https://github.com/arrowtype/recursive/issues/412
>	 
> <img width="677" alt="스크린샷 2020-12-05 01 45 03" src="https://user-images.githubusercontent.com/261579/101234704-9b614b00-368f-11eb-97c7-4673d4f01b27.png">
>
> Do you know any tips to fix this?

From From https://github.com/googlefonts/fontbakery/blame/8cf2698f36d8e6562444c0f8b09104bc75e709c5/Lib/fontbakery/profiles/glyf.py it looks like @simoncozens recently authored this check. 

Simon, Do you know any tips to fix this? 

I guess if this is resolved the tips should be added to the fontbakery check metadata :)

**Comment by aaronbell** [comment]
Looks like ufo2ft has a [mechanism to flatten components on export](https://github.com/googlefonts/fontbakery/issues/2961#issuecomment-733745539) (by adding a filter to the UFO). Maybe I’ll use GlyphsLib then ufo2ft rather than a direct fontMake export. Should solve it.

**Comment by simoncozens** [comment]
For now that’s the best answer. I’ll work on getting a fontmake flag to do it.

**Comment by minjooham** [comment]
@aaronbell @simoncozens Could fontmake solve this? or do you have workaround proposal for now?

**Comment by simoncozens** [comment]
I have pull requests against fontmake and ufo2ft. If/when they are merged, it will be easy to solve. Until then, convert to UFO and add the lib key that Aaron mentions above.

**Comment by aaronbell** [comment]
@minjooham I will take care of it in a build script to convert to UFO and then build the font. No need to change the source format in the repro.

**Comment by minjooham** [comment]
Great! Thanks a lot @aaronbell

**Comment by davelab6** [comment]
What is the current status of this?

**Comment by aaronbell** [comment]
@davelab6 i will be able to resolve it in the build script. :)

**Comment by aaronbell** [comment]
The branch / PR that I created flattens components and resolves this issue :)
